import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const PROJECT_URL = Deno.env.get("SUPABASE_URL")!;
const ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY")!;
const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const KV_TABLE = "kv_store_c0d15c17";
const DEFAULT_FIGMA_FILE_KEY = "tbDPLtFhYYORMKo4IAKmck";
const APP_ORIGIN = Deno.env.get("APP_ORIGIN") || "https://goutham-sheshi.github.io";
const corsHeaders = {"Access-Control-Allow-Origin":APP_ORIGIN,"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"GET, OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json"}});
const service=()=>createClient(PROJECT_URL,SERVICE_KEY);
async function requireUser(req:Request){const auth=req.headers.get("Authorization");if(!auth?.startsWith("Bearer "))return null;const client=createClient(PROJECT_URL,ANON_KEY,{global:{headers:{Authorization:auth}}});const {data,error}=await client.auth.getUser();return error||!data.user?null:data.user;}
async function kvGet(key:string){const {data,error}=await service().from(KV_TABLE).select("value").eq("key",key).maybeSingle();if(error)throw new Error(error.message);return data?.value;}
async function kvSet(key:string,value:unknown){const {error}=await service().from(KV_TABLE).upsert({key,value});if(error)throw new Error(error.message);}
async function refreshImages(fileKey:string,nodeIds:string[],token:string){const ids=[...new Set(nodeIds.filter(Boolean))];const batches:string[][]=[];for(let i=0;i<ids.length;i+=50)batches.push(ids.slice(i,i+50));const images:Record<string,string>={};let cursor=0;const worker=async()=>{while(true){const batch=batches[cursor++];if(!batch)return;try{const url=new URL(`https://api.figma.com/v1/images/${fileKey}`);url.searchParams.set("ids",batch.join(","));url.searchParams.set("format","png");url.searchParams.set("scale","0.5");const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);const res=await fetch(url,{headers:{"X-Figma-Token":token},signal:controller.signal});clearTimeout(timer);if(!res.ok)continue;const payload=await res.json();if(payload?.images&&typeof payload.images==="object")for(const [id,value] of Object.entries(payload.images))if(typeof value==="string"&&value)images[id]=value;}catch{}}};await Promise.all(Array.from({length:Math.min(4,batches.length)},worker));return images;}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});if(req.method!=="GET")return json({error:"Method not allowed"},405);if(!(await requireUser(req)))return json({error:"Unauthorized"},401);try{const stored=await kvGet("figma_resources_v1");const lastSyncedAt=await kvGet("figma_last_synced_at");const resources=Array.isArray(stored)?stored:[];if(!resources.length)return json({resources:[],lastSyncedAt:lastSyncedAt??null,refreshedPreviews:0});const token=await kvGet("figma_token");if(!token||typeof token!=="string")return json({resources,lastSyncedAt:lastSyncedAt??null,refreshedPreviews:0});const byFile=new Map<string,string[]>();for(const resource of resources){const fileKey=String(resource?.fileKey||DEFAULT_FIGMA_FILE_KEY);const nodeId=String(resource?.nodeId||"");if(!nodeId)continue;const list=byFile.get(fileKey)||[];list.push(nodeId);byFile.set(fileKey,list);}const imageMaps=new Map<string,Record<string,string>>();for(const [fileKey,ids] of byFile)imageMaps.set(fileKey,await refreshImages(fileKey,ids,token));let refreshedPreviews=0;const refreshed=resources.map((resource:any)=>{const fileKey=String(resource?.fileKey||DEFAULT_FIGMA_FILE_KEY);const image=imageMaps.get(fileKey)?.[resource?.nodeId]||null;if(image)refreshedPreviews++;return {...resource,thumbnail:image||resource.thumbnail||null,thumbnailUrl:image||resource.thumbnailUrl||resource.thumbnail||null};});if(refreshedPreviews>0)await kvSet("figma_resources_v1",refreshed);return json({resources:refreshed,lastSyncedAt:lastSyncedAt??null,refreshedPreviews});}catch(error){return json({error:"Failed to load Figma resources",detail:error instanceof Error?error.message:String(error)},500);}});
