import React, { useEffect, useState } from 'react'
import { getMyProfile, getRegisteredAccounts, type VaultProfile } from './authApi'
import type { UserRole } from './types'
import ResetUserPasswordModal from './components/ResetUserPasswordModal'
import { deleteUserProfile, getAllProfiles, updateUserRole, updateUserStatus } from './userManagementApi'

const roleLabel = (role: UserRole) => role === 'standard' ? 'User' : role === 'teammate' ? 'Teammate' : role === 'admin' ? 'Admin' : 'User'

export default function AdminUsers() {
  const [users, setUsers] = useState<VaultProfile[]>([])
  const [currentUser, setCurrentUser] = useState<VaultProfile | null>(null)
  const [registeredAccounts, setRegisteredAccounts] = useState<Record<string, any>>({})
  const [loading, setLoading] = useState(true)
  const [busyId, setBusyId] = useState<string | null>(null)
  const [notice, setNotice] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [selectedUserForReset, setSelectedUserForReset] = useState<VaultProfile | null>(null)

  const loadUsers = async () => { setLoading(true); setError(null); try { setUsers(await getAllProfiles()); setRegisteredAccounts(getRegisteredAccounts()) } catch (e: any) { setError(e?.message || 'Failed to load user list') } finally { setLoading(false) } }
  useEffect(() => { getMyProfile().then(setCurrentUser); loadUsers() }, [])
  const run = async (id: string, fn: () => Promise<void>) => { setBusyId(id); setError(null); try { await fn(); await loadUsers() } catch (e: any) { setError(e?.message || 'Update failed') } finally { setBusyId(null) } }
  const isSelf = (u: VaultProfile) => !!currentUser && (u.id === currentUser.id || u.email.toLowerCase() === currentUser.email.toLowerCase())

  if (loading) return <div className="p-12 text-center text-[13px] text-[var(--ink-45)]">Loading user list...</div>
  return <div className="flex-1 self-stretch w-full overflow-y-auto"><div className="px-8 py-6 max-w-[1400px]">
    <div className="flex items-start justify-between gap-4 mb-6"><div><h1 className="font-display text-[22px] font-bold text-[var(--ink)] tracking-tight">User Management & Access Control</h1><p className="text-[13px] text-[var(--ink-45)] mt-1">Assign Admin, Teammate, or User access. Teammates can upload files without receiving admin controls.</p></div><button onClick={loadUsers} className="px-3.5 py-2 rounded-lg border border-[var(--line-soft)] bg-white text-[12px] font-semibold">Refresh List</button></div>
    {notice && <div className="mb-5 p-3 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-[12px]">{notice}</div>}
    {error && <div className="mb-5 p-3 rounded-xl bg-red-50 border border-red-200 text-red-700 text-[12px]">{error}</div>}
    <div className="mb-5 grid grid-cols-1 md:grid-cols-3 gap-3 text-[12px]"><div className="p-4 rounded-xl border border-amber-200 bg-amber-50"><b>Admin</b><br/>View, download, upload, and full admin management.</div><div className="p-4 rounded-xl border border-blue-200 bg-blue-50"><b>Teammate</b><br/>View, download, and upload files. No admin controls.</div><div className="p-4 rounded-xl border border-slate-200 bg-slate-50"><b>User</b><br/>View and download only.</div></div>
    <div className="bg-white border border-[var(--line-soft)] rounded-2xl overflow-hidden shadow-sm"><div className="overflow-x-auto"><table className="w-full text-left border-collapse"><thead className="bg-[var(--canvas)] border-b border-[var(--line-soft)] text-[11px] text-[var(--ink-45)] uppercase tracking-wider"><tr><th className="px-5 py-3.5">User</th><th className="px-5 py-3.5">Email</th><th className="px-5 py-3.5">Role</th><th className="px-5 py-3.5">Status</th><th className="px-5 py-3.5 text-right">Actions</th></tr></thead><tbody className="divide-y divide-[var(--line-soft)] text-[12.5px]">{users.map(u => { const self = isSelf(u); const busy = busyId === u.id; const displayRole = u.role === 'standard' ? 'user' : u.role; return <tr key={u.id}><td className="px-5 py-4 font-semibold">{u.full_name || 'User'}{self && <span className="ml-2 text-[9px] text-blue-700">YOU</span>}</td><td className="px-5 py-4 font-mono text-[12px] text-[var(--ink-70)]">{u.email}</td><td className="px-5 py-4">{self ? <span className="font-semibold">{roleLabel(u.role)}</span> : <select value={displayRole} disabled={busy} onChange={e => run(u.id, async () => { await updateUserRole(u.id, e.target.value as UserRole, u.email); setNotice(`${u.full_name || u.email} is now ${roleLabel(e.target.value as UserRole)}.`) })} className="rounded-lg border border-[var(--line-soft)] px-2 py-1 bg-white text-[12px]"><option value="admin">Admin</option><option value="teammate">Teammate</option><option value="user">User</option></select>}</td><td className="px-5 py-4"><span className="px-2 py-1 rounded-full text-[10px] font-bold uppercase">{u.status}</span></td><td className="px-5 py-4 text-right"><div className="flex justify-end gap-2 flex-wrap">{!self && u.status !== 'approved' && <button disabled={busy} onClick={() => run(u.id, async () => { await updateUserStatus(u.id, 'approved', u.email); setNotice(`Approved ${u.full_name || u.email}.`) })} className="px-2.5 py-1 rounded-lg text-[11px] bg-emerald-50 text-emerald-700 border border-emerald-200">Approve</button>}{!self && u.status !== 'rejected' && <button disabled={busy} onClick={() => run(u.id, async () => { await updateUserStatus(u.id, 'rejected', u.email); setNotice(`Rejected ${u.full_name || u.email}.`) })} className="px-2.5 py-1 rounded-lg text-[11px] bg-yellow-50 text-yellow-800 border border-yellow-200">Reject</button>}<button onClick={() => setSelectedUserForReset(u)} className="px-2.5 py-1 rounded-lg text-[11px] border">Reset Password</button>{!self && <button disabled={busy} onClick={() => { if (window.confirm(`Delete ${u.full_name || u.email}?`)) run(u.id, async () => { await deleteUserProfile(u.id, u.email); setNotice(`Deleted ${u.full_name || u.email}.`) }) }} className="px-2.5 py-1 rounded-lg text-[11px] text-red-700 border border-red-200">Delete</button>}</div></td></tr> })}</tbody></table></div></div>
  </div>{selectedUserForReset && <ResetUserPasswordModal user={selectedUserForReset} onClose={() => setSelectedUserForReset(null)} onSuccess={() => { setNotice(`Password reset for ${selectedUserForReset.full_name || selectedUserForReset.email}.`); setSelectedUserForReset(null); loadUsers() }} />}</div>
}
