import { FormEvent, useEffect, useState } from 'react'
import type { Session } from '@supabase/supabase-js'
import { supabase } from './lib/supabase'
import { getMyProfile, type VaultProfile, vaultUserAdmin } from './authApi'

const field={width:'100%',boxSizing:'border-box' as const,padding:'14px 16px',border:'1px solid #d1d5db',borderRadius:12,marginBottom:16,fontSize:16}
const button={width:'100%',padding:14,border:0,borderRadius:12,background:'#E05A1C',color:'#fff',fontWeight:700,fontSize:16,cursor:'pointer' as const}
const validEmail=(v:string)=>/^[^\s@]+@sheshi\.ai$/i.test(v.trim())
const recoveryUrl=()=>`${window.location.origin}${window.location.pathname}?reset=1`
const isRecovery=()=>new URLSearchParams(window.location.search).get('reset')==='1'||window.location.hash.includes('type=recovery')

export default function AuthGate({children}:{children:React.ReactNode}){
 const [session,setSession]=useState<Session|null>(null),[profile,setProfile]=useState<VaultProfile|null>(null),[loading,setLoading]=useState(true)
 const [mode,setMode]=useState<'signin'|'forgot'|'request'>('signin'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState('')
 const [recovery,setRecovery]=useState(isRecovery()),[recoveryReady,setRecoveryReady]=useState(false),[nextPassword,setNextPassword]=useState(''),[confirm,setConfirm]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 const load=async()=>{try{let p=await getMyProfile();if(!p){const r=await vaultUserAdmin('ensure_profile');p=r.profile||await getMyProfile()}setProfile(p)}catch{setProfile(null);setMessage('Account setup could not be completed. Please sign out and try again.')}finally{setLoading(false)}}
 useEffect(()=>{let alive=true;const boot=async()=>{const {data}=await supabase.auth.getSession();if(!alive)return;setSession(data.session);if(isRecovery()){setRecovery(true);setRecoveryReady(Boolean(data.session));setLoading(false)}else if(data.session)await load();else setLoading(false)};void boot();const {data:{subscription}}=supabase.auth.onAuthStateChange((event,s)=>{if(!alive)return;setSession(s);if(event==='PASSWORD_RECOVERY'||isRecovery()){setRecovery(true);setRecoveryReady(Boolean(s));setLoading(false);return}if(s)void load();else{setProfile(null);setLoading(false)}});return()=>{alive=false;subscription.unsubscribe()}},[])
 const signIn=async(e:FormEvent)=>{e.preventDefault();if(!validEmail(email))return setMessage('Only @sheshi.ai email addresses are eligible.');setBusy(true);setMessage('');const {error}=await supabase.auth.signInWithPassword({email:email.trim().toLowerCase(),password});setBusy(false);if(error)setMessage('Could not sign in with those details.')}
 const request=async(e:FormEvent)=>{e.preventDefault();if(!validEmail(email))return setMessage('Only @sheshi.ai email addresses are eligible.');if(password.length<8)return setMessage('Use at least 8 characters.');setBusy(true);setMessage('');const {data,error}=await supabase.auth.signUp({email:email.trim().toLowerCase(),password,options:{data:{full_name:name.trim()}}});if(!error&&data.session){try{await vaultUserAdmin('request_access',{fullName:name.trim()});await supabase.auth.signOut()}catch{}}setBusy(false);setMessage(error?'Could not submit your access request.':'Your access request has been submitted for admin approval.')}
 const forgot=async(e:FormEvent)=>{e.preventDefault();if(!validEmail(email))return setMessage('Enter your @sheshi.ai email.');setBusy(true);setMessage('');const {error}=await supabase.auth.resetPasswordForEmail(email.trim().toLowerCase(),{redirectTo:recoveryUrl()});setBusy(false);if(error)setMessage(error.status===429||/rate/i.test(error.message)?'Too many reset emails were requested. Please wait and try again.':'Could not send the reset email. Please try again.');else setMessage('Reset link sent. Use the newest email link.')}
 const reset=async(e:FormEvent)=>{e.preventDefault();if(!recoveryReady)return setMessage('This reset link is invalid or expired. Request a new one.');if(nextPassword.length<8)return setMessage('Use at least 8 characters.');if(nextPassword!==confirm)return setMessage('Passwords do not match.');setBusy(true);const {error}=await supabase.auth.updateUser({password:nextPassword});setBusy(false);if(error)return setMessage('Could not update password. Request a fresh reset link.');window.history.replaceState({},document.title,window.location.pathname);await supabase.auth.signOut();setRecovery(false);setRecoveryReady(false);setMode('signin');setMessage('Password updated. Sign in with your new password.')}
 const initial=async(e:FormEvent)=>{e.preventDefault();if(nextPassword.length<8)return setMessage('Use at least 8 characters.');setBusy(true);try{await vaultUserAdmin('complete_initial_password_change',{password:nextPassword});await load()}catch(err){setMessage(err instanceof Error?err.message:'Could not update password.')}finally{setBusy(false)}}
 const logout=()=>void supabase.auth.signOut()
 if(loading)return <div style={{minHeight:'100vh',display:'grid',placeItems:'center'}}>Loading Sheshi Vault…</div>
 const shell=(content:React.ReactNode)=><main style={{minHeight:'100vh',display:'grid',placeItems:'center',padding:24,fontFamily:'Inter,system-ui,sans-serif',background:'#f8fafc'}}><div style={{width:'100%',maxWidth:480,background:'#fff',padding:32,borderRadius:20,boxShadow:'0 12px 40px rgba(15,23,42,.12)'}}>{content}</div></main>
 if(recovery)return shell(<form onSubmit={reset}><h1>Reset password</h1><p>{recoveryReady?'Choose a new password.':'This reset link is invalid or expired.'}</p>{recoveryReady&&<><input type='password' required minLength={8} autoComplete='new-password' placeholder='New password' value={nextPassword} onChange={e=>setNextPassword(e.target.value)} style={field}/><input type='password' required minLength={8} autoComplete='new-password' placeholder='Confirm new password' value={confirm} onChange={e=>setConfirm(e.target.value)} style={field}/><button disabled={busy} style={button}>{busy?'Updating…':'Update password'}</button></>}{message&&<p>{message}</p>}</form>)
 if(session&&profile?.status==='approved'&&profile.must_change_password)return shell(<form onSubmit={initial}><h1>Set your password</h1><p>Replace your temporary password before continuing.</p><input type='password' required minLength={8} autoComplete='new-password' placeholder='New password' value={nextPassword} onChange={e=>setNextPassword(e.target.value)} style={field}/><button disabled={busy} style={button}>Set password and continue</button>{message&&<p>{message}</p>}</form>)
 if(session&&profile?.status==='approved')return <>{children}</>
 if(session&&profile)return shell(<><h1>{profile.status==='pending'?'Access pending':'Access unavailable'}</h1><p>{profile.status==='pending'?'Your request is waiting for admin approval.':'This account has not been approved.'}</p><button onClick={logout} style={button}>Sign out</button></>)
 if(session&&!profile)return shell(<><h1>Account setup incomplete</h1><p>{message||'Your account exists but its Vault profile could not be created.'}</p><button onClick={()=>{setLoading(true);void load()}} style={button}>Try again</button><button onClick={logout} style={{...button,marginTop:10}}>Sign out</button></>)
 const submit=mode==='signin'?signIn:mode==='forgot'?forgot:request
 const title=mode==='signin'?'Sheshi Vault':mode==='forgot'?'Reset password':'Request access'
 return shell(<form onSubmit={submit}><div style={{width:52,height:52,borderRadius:16,display:'grid',placeItems:'center',background:'#E05A1C',color:'#fff',fontSize:26,fontWeight:800}}>S</div><h1 style={{fontSize:34,marginBottom:8}}>{title}</h1><p style={{color:'#64748b',marginBottom:24}}>{mode==='signin'?'Sign in with your approved @sheshi.ai account.':mode==='forgot'?'We will send a reset link to your email.':'Submit your @sheshi.ai account for approval.'}</p>{mode==='request'&&<input required placeholder='Full name' value={name} onChange={e=>setName(e.target.value)} style={field}/>}<input type='email' required placeholder='name@sheshi.ai' value={email} onChange={e=>setEmail(e.target.value)} style={field}/>{mode!=='forgot'&&<input type='password' required minLength={8} autoComplete={mode==='signin'?'current-password':'new-password'} placeholder='Password' value={password} onChange={e=>setPassword(e.target.value)} style={field}/>}<button disabled={busy} style={button}>{busy?'Please wait…':mode==='signin'?'Sign in':mode==='forgot'?'Send reset link':'Request access'}</button>{mode==='signin'&&<><button type='button' onClick={()=>{setMode('forgot');setMessage('')}} style={{...button,background:'transparent',color:'#b45309'}}>Forgot password?</button><button type='button' onClick={()=>{setMode('request');setMessage('')}} style={{...button,background:'transparent',color:'#b45309'}}>Need access? Request approval</button></>}{mode!=='signin'&&<button type='button' onClick={()=>{setMode('signin');setMessage('')}} style={{...button,background:'transparent',color:'#b45309'}}>Back to sign in</button>}{message&&<p style={{marginTop:16,color:message.includes('sent')||message.includes('submitted')||message.includes('updated')?'#166534':'#b91c1c'}}>{message}</p>}</form>)
}
