import React,{useEffect,useMemo,useState}from'react'
import{products}from'./data'
import{getManagedResources}from'./resourcesApi'
import{getEvents,type ManagedEvent}from'./eventsApi'
import type{Product,Resource,ResourceType}from'./types'

const Icon=({children}:{children:React.ReactNode})=><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{children}</svg>
const HomeIcon=()=> <Icon><path d="m3 10 9-7 9 7v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><path d="M9 22v-8h6v8"/></Icon>
const GridIcon=()=> <Icon><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></Icon>
const DownloadIcon=()=> <Icon><path d="M12 3v12M7 10l5 5 5-5M5 21h14"/></Icon>
const CalIcon=()=> <Icon><rect x="3" y="4" width="18" height="18" rx="2"/><path d="M16 2v4M8 2v4M3 10h18"/></Icon>
const ShieldIcon=()=> <Icon><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/></Icon>
const FileIcon=()=> <Icon><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z"/><path d="M14 2v6h6"/></Icon>
const PlayIcon=()=> <Icon><path d="m8 5 11 7-11 7z"/></Icon>
const Chevron=({open}:{open:boolean})=><span style={{transform:open?'rotate(90deg)':'rotate(0deg)',transition:'transform .15s'}}>›</span>

type View={kind:'home'}|{kind:'product';slug:string}|{kind:'all'}|{kind:'events'}|{kind:'admin'}
const productOf=(id:string)=>products.find(p=>p.id===id)
const localDate=(v:string)=>{const m=String(v).match(/^(\d{4})-(\d{2})-(\d{2})/);return m?new Date(+m[1],+m[2]-1,+m[3]):new Date(v)}
const upcoming=(e:ManagedEvent)=>{const d=localDate(e.event_date);d.setHours(0,0,0,0);const n=new Date();n.setHours(0,0,0,0);return d>=n}
const dateText=(v:string)=>localDate(v).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})

function ProductBadge({product}:{product?:Product}){if(!product)return null;return <span className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full text-[10px] font-semibold" style={{background:product.light,color:product.color}}><span className="w-1.5 h-1.5 rounded-full" style={{background:product.color}}/>{product.name}</span>}
function ResourceCard({resource}:{resource:Resource}){const p=productOf(resource.productId);const isVideo=resource.type==='video';return <div className="group bg-white border border-[var(--line-soft)] rounded-xl overflow-hidden flex flex-col hover:shadow-lg transition-shadow"><div className="h-40 bg-[var(--canvas-deep)] flex items-center justify-center overflow-hidden relative">{resource.thumbnail?<img src={resource.thumbnail} alt={resource.title} className="w-full h-full object-cover" loading="lazy" onError={e=>{e.currentTarget.style.display='none'}}/>:<FileIcon/>}{isVideo&&<div className="absolute inset-0 flex items-center justify-center bg-black/10"><span className="w-10 h-10 rounded-full bg-white/90 flex items-center justify-center"><PlayIcon/></span></div>}{resource.fileFormat&&<span className="absolute top-2 right-2 bg-white/95 rounded px-2 py-1 text-[9px] font-mono">{resource.fileFormat}</span>}</div><div className="p-3.5 flex flex-col gap-2 flex-1"><div className="line-clamp-2 text-[13px] font-semibold min-h-[36px]">{resource.title}</div><div className="flex items-center gap-2"><ProductBadge product={p}/>{resource.fileSize&&<span className="text-[10px] text-[var(--ink-45)]">{resource.fileSize}</span>}</div><div className="mt-auto flex justify-between items-center text-[11px]"><span className="text-[var(--ink-45)]">{resource.viewCount||0} views</span>{resource.sourceUrl&&<a href={resource.sourceUrl} target="_blank" rel="noreferrer" className="font-semibold text-[var(--ink)]">{isVideo?'Open Video':'Download'}</a>}</div></div></div>}
function ResourceGrid({items}:{items:Resource[]}){return items.length?<div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4">{items.map(x=><ResourceCard key={x.id} resource={x}/>)}</div>:<div className="py-14 text-center text-[13px] text-[var(--ink-45)]">No files here yet.</div>}
function EventCard({event,hero}:{event:ManagedEvent;hero?:boolean}){const p=productOf(event.product_id||'');const meta=[event.location,event.event_type].filter(Boolean).join(' · ');if(hero)return <div className="relative min-h-[220px] rounded-2xl overflow-hidden bg-[var(--canvas-deep)] text-white">{event.banner&&<img src={event.banner} className="absolute inset-0 w-full h-full object-cover" alt=""/>}<div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/30 to-black/10"/><div className="relative h-full min-h-[220px] p-6 flex flex-col justify-between"><ProductBadge product={p}/><div><div className="font-display text-[22px] font-bold">{event.title}</div><div className="text-[12px] text-white/75 mt-1">{dateText(event.event_date)}{meta?` · ${meta}`:''}</div></div></div></div>;return <div className="bg-white border border-[var(--line-soft)] rounded-xl overflow-hidden">{event.banner&&<img src={event.banner} className="w-full h-32 object-cover" alt=""/>}<div className="p-4"><ProductBadge product={p}/><div className="font-semibold text-[14px] mt-2">{event.title}</div><div className="text-[11px] text-[var(--ink-45)] mt-1">{dateText(event.event_date)}{meta?` · ${meta}`:''}</div></div></div>}
function Home({resources,events,onProduct}:{resources:Resource[];events:ManagedEvent[];onProduct:(s:string)=>void}){const next=events.filter(upcoming).sort((a,b)=>localDate(a.event_date).getTime()-localDate(b.event_date).getTime());const latest=[...resources].sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||''))).slice(0,5);return <main className="flex-1 overflow-y-auto"><div className="px-8 py-6 max-w-[1400px] space-y-9"><div><div className="text-[11px] font-mono text-[var(--ink-45)] uppercase tracking-wider">{new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</div><h1 className="font-display text-[26px] font-bold mt-1">Welcome back</h1></div><section><h2 className="font-display text-[15px] font-bold mb-3">Upcoming</h2>{next.length?<div className="grid grid-cols-1 lg:grid-cols-3 gap-4"><div className="lg:col-span-2"><EventCard event={next[0]} hero/></div><div className="flex flex-col gap-3">{next.slice(1,3).map(e=><EventCard key={e.id} event={e}/>)}</div></div>:<div className="text-[13px] text-[var(--ink-45)] py-6">No upcoming events.</div>}</section><section><h2 className="font-display text-[15px] font-bold mb-3">Products</h2><div className="grid grid-cols-2 sm:grid-cols-4 gap-3">{products.map(p=><button key={p.id} onClick={()=>onProduct(p.slug)} className="text-left rounded-xl border border-[var(--line-soft)] p-4"><div className="w-8 h-8 rounded-lg flex items-center justify-center font-bold mb-2" style={{background:p.light,color:p.color}}>{p.name[0]}</div><div className="font-semibold text-[13px]">{p.name}</div><div className="text-[11px] text-[var(--ink-45)] mt-1">{resources.filter(r=>r.productId===p.id).length} files</div></button>)}</div></section><section className="pb-8"><h2 className="font-display text-[15px] font-bold mb-3">Latest Resources</h2><ResourceGrid items={latest}/></section></div></main>}
function ProductPage({product,resources}:{product:Product;resources:Resource[]}){const items=resources.filter(r=>r.productId===product.id);const groups:[ResourceType,string][]=[['logo','Brand Assets'],['brochure','Brochures'],['video','Videos'],['document','Documents'],['other','Other Files']];return <main className="flex-1 overflow-y-auto"><div className="px-8 py-6 max-w-[1400px]"><div className="flex gap-4 items-center mb-8 pb-6 border-b border-[var(--line-soft)]"><div className="w-14 h-14 rounded-2xl flex items-center justify-center text-xl font-bold" style={{background:product.light,color:product.color}}>{product.name[0]}</div><div><h1 className="font-display text-[24px] font-bold">{product.name}</h1><p className="text-[13px] text-[var(--ink-45)]">{product.description}</p></div></div><div className="space-y-9 pb-8">{groups.map(([type,label])=>{const group=items.filter(x=>x.type===type);return group.length?<section key={type}><h2 className="font-display text-[15px] font-bold mb-3">{label}</h2><ResourceGrid items={group}/></section>:null})}{!items.length&&<div className="text-[13px] text-[var(--ink-45)] py-10">No files have been added for this product.</div>}</div></div></main>}
function AllResources({resources}:{resources:Resource[]}){const [product,setProduct]=useState('');const items=product?resources.filter(r=>r.productId===product):resources;return <main className="flex-1 overflow-y-auto"><div className="px-8 py-6 max-w-[1400px]"><h1 className="font-display text-[22px] font-bold mb-5">All Resources</h1><div className="flex gap-2 flex-wrap mb-5"><button onClick={()=>setProduct('')} className={`px-3 py-1.5 rounded-full text-[12px] ${!product?'bg-[var(--primary)] text-white':'bg-white border border-[var(--line-soft)]'}`}>All Products</button>{products.map(p=><button key={p.id} onClick={()=>setProduct(p.id)} className={`px-3 py-1.5 rounded-full text-[12px] ${product===p.id?'text-white':'bg-white border border-[var(--line-soft)]'}`} style={product===p.id?{background:p.color}:undefined}>{p.name}</button>)}</div><ResourceGrid items={items}/></div></main>}
function Events({events}:{events:ManagedEvent[]}){const future=events.filter(upcoming).sort((a,b)=>localDate(a.event_date).getTime()-localDate(b.event_date).getTime());const past=events.filter(e=>!upcoming(e)).sort((a,b)=>localDate(b.event_date).getTime()-localDate(a.event_date).getTime());return <main className="flex-1 overflow-y-auto"><div className="px-8 py-6 max-w-[1400px] space-y-8"><h1 className="font-display text-[22px] font-bold">Events</h1><section><h2 className="font-display text-[15px] font-bold mb-3">Upcoming</h2>{future.length?<div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">{future.map(e=><EventCard key={e.id} event={e}/>)}</div>:<div className="py-10 text-[13px] text-[var(--ink-45)]">No upcoming events.</div>}</section>{past.length>0&&<section><h2 className="font-display text-[15px] font-bold mb-3">Past</h2><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 opacity-70">{past.map(e=><EventCard key={e.id} event={e}/>)}</div></section>}</div></main>}
function Sidebar({view,onView}:{view:View;onView:(v:View)=>void}){const[open,setOpen]=useState(true);return <aside className="w-[236px] flex-shrink-0 flex flex-col bg-white border-r border-[var(--line)]"><div className="h-14 flex items-center px-4 border-b border-[var(--line-soft)]"><span className="font-display text-[15px] font-bold">Sheshi Vault</span></div><nav className="flex-1 overflow-y-auto px-2.5 py-3"><button onClick={()=>onView({kind:'home'})} className={`w-full flex gap-2.5 px-2.5 py-2 rounded-lg text-[13px] ${view.kind==='home'?'bg-[var(--primary)] text-white':'text-[var(--ink-70)]'}`}><HomeIcon/>Home</button><button onClick={()=>setOpen(!open)} className="w-full flex gap-2.5 px-2.5 py-2 rounded-lg text-[13px] text-[var(--ink-70)]"><GridIcon/><span className="flex-1 text-left">Products</span><Chevron open={open}/></button>{open&&<div className="ml-3 pl-3 border-l border-[var(--line-soft)]">{products.map(p=><button key={p.id} onClick={()=>onView({kind:'product',slug:p.slug})} className={`w-full flex gap-2 px-2.5 py-1.5 text-left rounded-md text-[12.5px] ${view.kind==='product'&&view.slug===p.slug?'font-semibold':'text-[var(--ink-45)]'}`}><span className="w-1.5 h-1.5 rounded-full mt-1.5" style={{background:p.color}}/>{p.name}</button>)}</div>}<button onClick={()=>onView({kind:'events'})} className={`w-full flex gap-2.5 px-2.5 py-2 rounded-lg text-[13px] ${view.kind==='events'?'bg-[var(--primary)] text-white':'text-[var(--ink-70)]'}`}><CalIcon/>Events</button><button onClick={()=>onView({kind:'all'})} className={`w-full flex gap-2.5 px-2.5 py-2 rounded-lg text-[13px] ${view.kind==='all'?'bg-[var(--primary)] text-white':'text-[var(--ink-70)]'}`}><DownloadIcon/>All Resources</button><div className="mt-2 pt-2 border-t border-[var(--line-soft)]"><button onClick={()=>onView({kind:'admin'})} className={`w-full flex gap-2.5 px-2.5 py-2 rounded-lg text-[13px] ${view.kind==='admin'?'bg-[var(--primary)] text-white':'text-[var(--ink-70)]'}`}><ShieldIcon/>Admin</button></div></nav></aside>}
export default function LiveApp(){const[view,setView]=useState<View>({kind:'home'});const[resources,setResources]=useState<Resource[]>([]);const[events,setEvents]=useState<ManagedEvent[]>([]);useEffect(()=>{getManagedResources().then(setResources).catch(()=>setResources([]));getEvents().then(setEvents).catch(()=>setEvents([]))},[]);const product=view.kind==='product'?products.find(p=>p.slug===view.slug):undefined;return <div className="flex h-screen bg-[var(--canvas)] overflow-hidden"><Sidebar view={view} onView={setView}/>{view.kind==='home'?<Home resources={resources} events={events} onProduct={slug=>setView({kind:'product',slug})}/>:view.kind==='product'&&product?<ProductPage product={product} resources={resources}/>:view.kind==='all'?<AllResources resources={resources}/>:view.kind==='events'?<Events events={events}/>:<main className="flex-1 flex items-center justify-center"><div className="text-center"><div className="font-display text-[16px] font-bold">Admin Console</div></div></main>}</div>}
